apiVersion: v1
kind: BuildConfig
metadata:
  name: simple-service
  labels:
    app: simple-service
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: simple-service:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    git:
      ref: master
      uri: https://github.com/in-the-keyhole/simple-dotnet-service.git
    dockerfile: |-
      FROM mcr.microsoft.com/dotnet/core/sdk:2.2 AS builder
      WORKDIR /app

      # Copy csproj and restore as distinct layers
      COPY *.csproj ./
      RUN dotnet restore

      # Copy everything else and build
      COPY . ./
      RUN dotnet publish -c Release -o out

      # Build runtime image
      FROM mcr.microsoft.com/dotnet/core/aspnet:2.2
      WORKDIR /app
      COPY --from=builder /app/out .
      ENTRYPOINT ["dotnet", "simple-dotnet-service.dll"]
    type: Dockerfile
  strategy:
    dockerStrategy:
      noCache: true
    type: Docker
  successfulBuildsHistoryLimit: 5
  triggers: []